/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package processmaker.pmio.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ClientAttributes
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-01T11:35:23.537+03:00")
public class ClientAttributes   {
  @SerializedName("secret")
  private String secret = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("personal_access_client")
  private Boolean personalAccessClient = null;

  @SerializedName("password_client")
  private Boolean passwordClient = null;

  @SerializedName("revoked")
  private Boolean revoked = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  public ClientAttributes secret(String secret) {
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @ApiModelProperty(example = "1WfPZS8TepSKgnure5FHUOyvT8340fQH8cz4ISN2", value = "")
  public String getSecret() {
    return secret;
  }

  public void setSecret(String secret) {
    this.secret = secret;
  }

  public ClientAttributes name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "Client Name", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ClientAttributes personalAccessClient(Boolean personalAccessClient) {
    this.personalAccessClient = personalAccessClient;
    return this;
  }

   /**
   * Get personalAccessClient
   * @return personalAccessClient
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getPersonalAccessClient() {
    return personalAccessClient;
  }

  public void setPersonalAccessClient(Boolean personalAccessClient) {
    this.personalAccessClient = personalAccessClient;
  }

  public ClientAttributes passwordClient(Boolean passwordClient) {
    this.passwordClient = passwordClient;
    return this;
  }

   /**
   * Get passwordClient
   * @return passwordClient
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getPasswordClient() {
    return passwordClient;
  }

  public void setPasswordClient(Boolean passwordClient) {
    this.passwordClient = passwordClient;
  }

  public ClientAttributes revoked(Boolean revoked) {
    this.revoked = revoked;
    return this;
  }

   /**
   * Get revoked
   * @return revoked
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getRevoked() {
    return revoked;
  }

  public void setRevoked(Boolean revoked) {
    this.revoked = revoked;
  }

  public ClientAttributes createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public ClientAttributes updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientAttributes clientAttributes = (ClientAttributes) o;
    return Objects.equals(this.secret, clientAttributes.secret) &&
        Objects.equals(this.name, clientAttributes.name) &&
        Objects.equals(this.personalAccessClient, clientAttributes.personalAccessClient) &&
        Objects.equals(this.passwordClient, clientAttributes.passwordClient) &&
        Objects.equals(this.revoked, clientAttributes.revoked) &&
        Objects.equals(this.createdAt, clientAttributes.createdAt) &&
        Objects.equals(this.updatedAt, clientAttributes.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secret, name, personalAccessClient, passwordClient, revoked, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientAttributes {\n");
    
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    personalAccessClient: ").append(toIndentedString(personalAccessClient)).append("\n");
    sb.append("    passwordClient: ").append(toIndentedString(passwordClient)).append("\n");
    sb.append("    revoked: ").append(toIndentedString(revoked)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

