/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package processmaker.pmio.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * InputOutputAttributes
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-01T11:35:23.537+03:00")
public class InputOutputAttributes   {
  @SerializedName("input_parameters")
  private Object inputParameters = null;

  @SerializedName("output_parameters")
  private Object outputParameters = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  public InputOutputAttributes inputParameters(Object inputParameters) {
    this.inputParameters = inputParameters;
    return this;
  }

   /**
   * Get inputParameters
   * @return inputParameters
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Object getInputParameters() {
    return inputParameters;
  }

  public void setInputParameters(Object inputParameters) {
    this.inputParameters = inputParameters;
  }

  public InputOutputAttributes outputParameters(Object outputParameters) {
    this.outputParameters = outputParameters;
    return this;
  }

   /**
   * Get outputParameters
   * @return outputParameters
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Object getOutputParameters() {
    return outputParameters;
  }

  public void setOutputParameters(Object outputParameters) {
    this.outputParameters = outputParameters;
  }

  public InputOutputAttributes createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public InputOutputAttributes updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InputOutputAttributes inputOutputAttributes = (InputOutputAttributes) o;
    return Objects.equals(this.inputParameters, inputOutputAttributes.inputParameters) &&
        Objects.equals(this.outputParameters, inputOutputAttributes.outputParameters) &&
        Objects.equals(this.createdAt, inputOutputAttributes.createdAt) &&
        Objects.equals(this.updatedAt, inputOutputAttributes.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputParameters, outputParameters, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InputOutputAttributes {\n");
    
    sb.append("    inputParameters: ").append(toIndentedString(inputParameters)).append("\n");
    sb.append("    outputParameters: ").append(toIndentedString(outputParameters)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

