/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package processmaker.pmio.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ProcessAttributes
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-01T11:35:23.537+03:00")
public class ProcessAttributes   {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("parent_process_id")
  private String parentProcessId = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("ACTIVE")
    ACTIVE("ACTIVE"),
    
    @SerializedName("INACTIVE")
    INACTIVE("INACTIVE"),
    
    @SerializedName("DISABLED")
    DISABLED("DISABLED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = StatusEnum.ACTIVE;

  /**
   * Gets or Sets durationBy
   */
  public enum DurationByEnum {
    @SerializedName("WORKING_DAYS")
    WORKING_DAYS("WORKING_DAYS"),
    
    @SerializedName("CALENDAR_DAYS")
    CALENDAR_DAYS("CALENDAR_DAYS");

    private String value;

    DurationByEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("duration_by")
  private DurationByEnum durationBy = DurationByEnum.WORKING_DAYS;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    @SerializedName("NORMAL")
    NORMAL("NORMAL"),
    
    @SerializedName("SUB_PROCESS")
    SUB_PROCESS("SUB_PROCESS");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = TypeEnum.NORMAL;

  @SerializedName("assignment")
  private Boolean assignment = false;

  /**
   * Gets or Sets designAccess
   */
  public enum DesignAccessEnum {
    @SerializedName("PUBLIC")
    PUBLIC("PUBLIC"),
    
    @SerializedName("PRIVATE")
    PRIVATE("PRIVATE");

    private String value;

    DesignAccessEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("design_access")
  private DesignAccessEnum designAccess = DesignAccessEnum.PUBLIC;

  @SerializedName("show_map")
  private Boolean showMap = true;

  @SerializedName("show_message")
  private Boolean showMessage = true;

  @SerializedName("show_delegate")
  private Boolean showDelegate = true;

  @SerializedName("show_dynaform")
  private Boolean showDynaform = false;

  @SerializedName("category_id")
  private String categoryId = null;

  @SerializedName("sub_category_id")
  private String subCategoryId = null;

  @SerializedName("create_user_id")
  private String createUserId = null;

  @SerializedName("debug")
  private Boolean debug = false;

  @SerializedName("dynaform_summary_id")
  private String dynaformSummaryId = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  public ProcessAttributes name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "Process_Title", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProcessAttributes description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "Some description", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ProcessAttributes parentProcessId(String parentProcessId) {
    this.parentProcessId = parentProcessId;
    return this;
  }

   /**
   * Get parentProcessId
   * @return parentProcessId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b11", value = "")
  public String getParentProcessId() {
    return parentProcessId;
  }

  public void setParentProcessId(String parentProcessId) {
    this.parentProcessId = parentProcessId;
  }

  public ProcessAttributes status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ProcessAttributes durationBy(DurationByEnum durationBy) {
    this.durationBy = durationBy;
    return this;
  }

   /**
   * Get durationBy
   * @return durationBy
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DurationByEnum getDurationBy() {
    return durationBy;
  }

  public void setDurationBy(DurationByEnum durationBy) {
    this.durationBy = durationBy;
  }

  public ProcessAttributes type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public ProcessAttributes assignment(Boolean assignment) {
    this.assignment = assignment;
    return this;
  }

   /**
   * Get assignment
   * @return assignment
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAssignment() {
    return assignment;
  }

  public void setAssignment(Boolean assignment) {
    this.assignment = assignment;
  }

  public ProcessAttributes designAccess(DesignAccessEnum designAccess) {
    this.designAccess = designAccess;
    return this;
  }

   /**
   * Get designAccess
   * @return designAccess
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DesignAccessEnum getDesignAccess() {
    return designAccess;
  }

  public void setDesignAccess(DesignAccessEnum designAccess) {
    this.designAccess = designAccess;
  }

  public ProcessAttributes showMap(Boolean showMap) {
    this.showMap = showMap;
    return this;
  }

   /**
   * Get showMap
   * @return showMap
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShowMap() {
    return showMap;
  }

  public void setShowMap(Boolean showMap) {
    this.showMap = showMap;
  }

  public ProcessAttributes showMessage(Boolean showMessage) {
    this.showMessage = showMessage;
    return this;
  }

   /**
   * Get showMessage
   * @return showMessage
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShowMessage() {
    return showMessage;
  }

  public void setShowMessage(Boolean showMessage) {
    this.showMessage = showMessage;
  }

  public ProcessAttributes showDelegate(Boolean showDelegate) {
    this.showDelegate = showDelegate;
    return this;
  }

   /**
   * Get showDelegate
   * @return showDelegate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShowDelegate() {
    return showDelegate;
  }

  public void setShowDelegate(Boolean showDelegate) {
    this.showDelegate = showDelegate;
  }

  public ProcessAttributes showDynaform(Boolean showDynaform) {
    this.showDynaform = showDynaform;
    return this;
  }

   /**
   * Get showDynaform
   * @return showDynaform
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShowDynaform() {
    return showDynaform;
  }

  public void setShowDynaform(Boolean showDynaform) {
    this.showDynaform = showDynaform;
  }

  public ProcessAttributes categoryId(String categoryId) {
    this.categoryId = categoryId;
    return this;
  }

   /**
   * Get categoryId
   * @return categoryId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b22", value = "")
  public String getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  public ProcessAttributes subCategoryId(String subCategoryId) {
    this.subCategoryId = subCategoryId;
    return this;
  }

   /**
   * Get subCategoryId
   * @return subCategoryId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b33", value = "")
  public String getSubCategoryId() {
    return subCategoryId;
  }

  public void setSubCategoryId(String subCategoryId) {
    this.subCategoryId = subCategoryId;
  }

  public ProcessAttributes createUserId(String createUserId) {
    this.createUserId = createUserId;
    return this;
  }

   /**
   * Get createUserId
   * @return createUserId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b44", value = "")
  public String getCreateUserId() {
    return createUserId;
  }

  public void setCreateUserId(String createUserId) {
    this.createUserId = createUserId;
  }

  public ProcessAttributes debug(Boolean debug) {
    this.debug = debug;
    return this;
  }

   /**
   * Get debug
   * @return debug
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getDebug() {
    return debug;
  }

  public void setDebug(Boolean debug) {
    this.debug = debug;
  }

  public ProcessAttributes dynaformSummaryId(String dynaformSummaryId) {
    this.dynaformSummaryId = dynaformSummaryId;
    return this;
  }

   /**
   * Get dynaformSummaryId
   * @return dynaformSummaryId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b55", value = "")
  public String getDynaformSummaryId() {
    return dynaformSummaryId;
  }

  public void setDynaformSummaryId(String dynaformSummaryId) {
    this.dynaformSummaryId = dynaformSummaryId;
  }

  public ProcessAttributes createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public ProcessAttributes updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessAttributes processAttributes = (ProcessAttributes) o;
    return Objects.equals(this.name, processAttributes.name) &&
        Objects.equals(this.description, processAttributes.description) &&
        Objects.equals(this.parentProcessId, processAttributes.parentProcessId) &&
        Objects.equals(this.status, processAttributes.status) &&
        Objects.equals(this.durationBy, processAttributes.durationBy) &&
        Objects.equals(this.type, processAttributes.type) &&
        Objects.equals(this.assignment, processAttributes.assignment) &&
        Objects.equals(this.designAccess, processAttributes.designAccess) &&
        Objects.equals(this.showMap, processAttributes.showMap) &&
        Objects.equals(this.showMessage, processAttributes.showMessage) &&
        Objects.equals(this.showDelegate, processAttributes.showDelegate) &&
        Objects.equals(this.showDynaform, processAttributes.showDynaform) &&
        Objects.equals(this.categoryId, processAttributes.categoryId) &&
        Objects.equals(this.subCategoryId, processAttributes.subCategoryId) &&
        Objects.equals(this.createUserId, processAttributes.createUserId) &&
        Objects.equals(this.debug, processAttributes.debug) &&
        Objects.equals(this.dynaformSummaryId, processAttributes.dynaformSummaryId) &&
        Objects.equals(this.createdAt, processAttributes.createdAt) &&
        Objects.equals(this.updatedAt, processAttributes.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, parentProcessId, status, durationBy, type, assignment, designAccess, showMap, showMessage, showDelegate, showDynaform, categoryId, subCategoryId, createUserId, debug, dynaformSummaryId, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessAttributes {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    parentProcessId: ").append(toIndentedString(parentProcessId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    durationBy: ").append(toIndentedString(durationBy)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    assignment: ").append(toIndentedString(assignment)).append("\n");
    sb.append("    designAccess: ").append(toIndentedString(designAccess)).append("\n");
    sb.append("    showMap: ").append(toIndentedString(showMap)).append("\n");
    sb.append("    showMessage: ").append(toIndentedString(showMessage)).append("\n");
    sb.append("    showDelegate: ").append(toIndentedString(showDelegate)).append("\n");
    sb.append("    showDynaform: ").append(toIndentedString(showDynaform)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    subCategoryId: ").append(toIndentedString(subCategoryId)).append("\n");
    sb.append("    createUserId: ").append(toIndentedString(createUserId)).append("\n");
    sb.append("    debug: ").append(toIndentedString(debug)).append("\n");
    sb.append("    dynaformSummaryId: ").append(toIndentedString(dynaformSummaryId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

