/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package processmaker.pmio.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * TaskInstanceAttributes
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-01T11:35:23.537+03:00")
public class TaskInstanceAttributes   {
  @SerializedName("task_id")
  private String taskId = null;

  @SerializedName("instance_id")
  private String instanceId = null;

  @SerializedName("group_id")
  private String groupId = null;

  @SerializedName("user_id")
  private String userId = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    @SerializedName("INITIAL")
    INITIAL("INITIAL"),
    
    @SerializedName("DELEGATED")
    DELEGATED("DELEGATED"),
    
    @SerializedName("STARTED")
    STARTED("STARTED"),
    
    @SerializedName("CANCELLED")
    CANCELLED("CANCELLED"),
    
    @SerializedName("FINISHED")
    FINISHED("FINISHED"),
    
    @SerializedName("COMPLETE")
    COMPLETE("COMPLETE"),
    
    @SerializedName("PAUSED")
    PAUSED("PAUSED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = StatusEnum.INITIAL;

  /**
   * Gets or Sets priority
   */
  public enum PriorityEnum {
    @SerializedName("1")
    _1("1"),
    
    @SerializedName("2")
    _2("2"),
    
    @SerializedName("3")
    _3("3"),
    
    @SerializedName("4")
    _4("4"),
    
    @SerializedName("5")
    _5("5");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("priority")
  private PriorityEnum priority = PriorityEnum._3;

  @SerializedName("delegate_date")
  private String delegateDate = null;

  @SerializedName("start_date")
  private String startDate = null;

  @SerializedName("finish_date")
  private String finishDate = null;

  @SerializedName("task_due_date")
  private String taskDueDate = null;

  @SerializedName("risk_date")
  private String riskDate = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("instance_overdue_percentage")
  private Double instanceOverduePercentage = null;

  @SerializedName("data")
  private String data = null;

  @SerializedName("content")
  private String content = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  public TaskInstanceAttributes taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b11", required = true, value = "")
  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public TaskInstanceAttributes instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * Get instanceId
   * @return instanceId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b11", required = true, value = "")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  public TaskInstanceAttributes groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b11", value = "")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public TaskInstanceAttributes userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "9d705617-cc29-482a-85ff-7f7292f72b11", value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public TaskInstanceAttributes status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public TaskInstanceAttributes priority(PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public PriorityEnum getPriority() {
    return priority;
  }

  public void setPriority(PriorityEnum priority) {
    this.priority = priority;
  }

  public TaskInstanceAttributes delegateDate(String delegateDate) {
    this.delegateDate = delegateDate;
    return this;
  }

   /**
   * Get delegateDate
   * @return delegateDate
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getDelegateDate() {
    return delegateDate;
  }

  public void setDelegateDate(String delegateDate) {
    this.delegateDate = delegateDate;
  }

  public TaskInstanceAttributes startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public TaskInstanceAttributes finishDate(String finishDate) {
    this.finishDate = finishDate;
    return this;
  }

   /**
   * Get finishDate
   * @return finishDate
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getFinishDate() {
    return finishDate;
  }

  public void setFinishDate(String finishDate) {
    this.finishDate = finishDate;
  }

  public TaskInstanceAttributes taskDueDate(String taskDueDate) {
    this.taskDueDate = taskDueDate;
    return this;
  }

   /**
   * Get taskDueDate
   * @return taskDueDate
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getTaskDueDate() {
    return taskDueDate;
  }

  public void setTaskDueDate(String taskDueDate) {
    this.taskDueDate = taskDueDate;
  }

  public TaskInstanceAttributes riskDate(String riskDate) {
    this.riskDate = riskDate;
    return this;
  }

   /**
   * Get riskDate
   * @return riskDate
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getRiskDate() {
    return riskDate;
  }

  public void setRiskDate(String riskDate) {
    this.riskDate = riskDate;
  }

  public TaskInstanceAttributes duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public TaskInstanceAttributes instanceOverduePercentage(Double instanceOverduePercentage) {
    this.instanceOverduePercentage = instanceOverduePercentage;
    return this;
  }

   /**
   * Get instanceOverduePercentage
   * @return instanceOverduePercentage
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getInstanceOverduePercentage() {
    return instanceOverduePercentage;
  }

  public void setInstanceOverduePercentage(Double instanceOverduePercentage) {
    this.instanceOverduePercentage = instanceOverduePercentage;
  }

  public TaskInstanceAttributes data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public TaskInstanceAttributes content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public TaskInstanceAttributes createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public TaskInstanceAttributes updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskInstanceAttributes taskInstanceAttributes = (TaskInstanceAttributes) o;
    return Objects.equals(this.taskId, taskInstanceAttributes.taskId) &&
        Objects.equals(this.instanceId, taskInstanceAttributes.instanceId) &&
        Objects.equals(this.groupId, taskInstanceAttributes.groupId) &&
        Objects.equals(this.userId, taskInstanceAttributes.userId) &&
        Objects.equals(this.status, taskInstanceAttributes.status) &&
        Objects.equals(this.priority, taskInstanceAttributes.priority) &&
        Objects.equals(this.delegateDate, taskInstanceAttributes.delegateDate) &&
        Objects.equals(this.startDate, taskInstanceAttributes.startDate) &&
        Objects.equals(this.finishDate, taskInstanceAttributes.finishDate) &&
        Objects.equals(this.taskDueDate, taskInstanceAttributes.taskDueDate) &&
        Objects.equals(this.riskDate, taskInstanceAttributes.riskDate) &&
        Objects.equals(this.duration, taskInstanceAttributes.duration) &&
        Objects.equals(this.instanceOverduePercentage, taskInstanceAttributes.instanceOverduePercentage) &&
        Objects.equals(this.data, taskInstanceAttributes.data) &&
        Objects.equals(this.content, taskInstanceAttributes.content) &&
        Objects.equals(this.createdAt, taskInstanceAttributes.createdAt) &&
        Objects.equals(this.updatedAt, taskInstanceAttributes.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskId, instanceId, groupId, userId, status, priority, delegateDate, startDate, finishDate, taskDueDate, riskDate, duration, instanceOverduePercentage, data, content, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskInstanceAttributes {\n");
    
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    delegateDate: ").append(toIndentedString(delegateDate)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    finishDate: ").append(toIndentedString(finishDate)).append("\n");
    sb.append("    taskDueDate: ").append(toIndentedString(taskDueDate)).append("\n");
    sb.append("    riskDate: ").append(toIndentedString(riskDate)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    instanceOverduePercentage: ").append(toIndentedString(instanceOverduePercentage)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

