/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package processmaker.pmio.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * TaskConnectorAttributes
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-01T11:35:23.537+03:00")
public class TaskConnectorAttributes   {
  @SerializedName("task_id")
  private Integer taskId = null;

  @SerializedName("connector_class")
  private String connectorClass = "HttpConnector";

  @SerializedName("input_parameters")
  private String inputParameters = "[]";

  @SerializedName("output_parameters")
  private String outputParameters = "[]";

  @SerializedName("async_before")
  private Boolean asyncBefore = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("updated_at")
  private String updatedAt = null;

  public TaskConnectorAttributes taskId(Integer taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTaskId() {
    return taskId;
  }

  public void setTaskId(Integer taskId) {
    this.taskId = taskId;
  }

  public TaskConnectorAttributes connectorClass(String connectorClass) {
    this.connectorClass = connectorClass;
    return this;
  }

   /**
   * Get connectorClass
   * @return connectorClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getConnectorClass() {
    return connectorClass;
  }

  public void setConnectorClass(String connectorClass) {
    this.connectorClass = connectorClass;
  }

  public TaskConnectorAttributes inputParameters(String inputParameters) {
    this.inputParameters = inputParameters;
    return this;
  }

   /**
   * Get inputParameters
   * @return inputParameters
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInputParameters() {
    return inputParameters;
  }

  public void setInputParameters(String inputParameters) {
    this.inputParameters = inputParameters;
  }

  public TaskConnectorAttributes outputParameters(String outputParameters) {
    this.outputParameters = outputParameters;
    return this;
  }

   /**
   * Get outputParameters
   * @return outputParameters
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOutputParameters() {
    return outputParameters;
  }

  public void setOutputParameters(String outputParameters) {
    this.outputParameters = outputParameters;
  }

  public TaskConnectorAttributes asyncBefore(Boolean asyncBefore) {
    this.asyncBefore = asyncBefore;
    return this;
  }

   /**
   * Get asyncBefore
   * @return asyncBefore
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAsyncBefore() {
    return asyncBefore;
  }

  public void setAsyncBefore(Boolean asyncBefore) {
    this.asyncBefore = asyncBefore;
  }

  public TaskConnectorAttributes createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public TaskConnectorAttributes updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2017-01-01T00:00:00+00:00", value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskConnectorAttributes taskConnectorAttributes = (TaskConnectorAttributes) o;
    return Objects.equals(this.taskId, taskConnectorAttributes.taskId) &&
        Objects.equals(this.connectorClass, taskConnectorAttributes.connectorClass) &&
        Objects.equals(this.inputParameters, taskConnectorAttributes.inputParameters) &&
        Objects.equals(this.outputParameters, taskConnectorAttributes.outputParameters) &&
        Objects.equals(this.asyncBefore, taskConnectorAttributes.asyncBefore) &&
        Objects.equals(this.createdAt, taskConnectorAttributes.createdAt) &&
        Objects.equals(this.updatedAt, taskConnectorAttributes.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taskId, connectorClass, inputParameters, outputParameters, asyncBefore, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskConnectorAttributes {\n");
    
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    connectorClass: ").append(toIndentedString(connectorClass)).append("\n");
    sb.append("    inputParameters: ").append(toIndentedString(inputParameters)).append("\n");
    sb.append("    outputParameters: ").append(toIndentedString(outputParameters)).append("\n");
    sb.append("    asyncBefore: ").append(toIndentedString(asyncBefore)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

